<?php
use MediaWiki\Output\OutputPage;
use MediaWiki\Skin\Skin;

# This file was automatically generated by the MediaWiki 1.44.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry

use phpDocumentor\Reflection\PseudoTypes\True_;
use MediaWiki\MediaWikiServices;

if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}




## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "GnosPedia";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
## Dynamic server based on subdomain
if (isset($_SERVER['HTTP_HOST'])) {
    $wgServer = "http://" . $_SERVER['HTTP_HOST'];
} else {
    $wgServer = "http://13.233.126.84";
}

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
	'icon' => "$wgResourceBasePath/resources/assets/change-your-logo-icon.svg",
];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "";
$wgPasswordSender = "";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "sqlite";
$wgDBserver = "";

# Use relative paths for SQLite databases
$wgDBname = 'azwiki';
$wgDBuser = '';
$wgDBpassword = '';

# SQLite-specific settings
$wgSQLiteDataDir = __DIR__ . '/data';

# Ensure the data directory exists and is writable
if ( !is_writable( $wgSQLiteDataDir ) ) {
    die( "Error: The data directory ({$wgSQLiteDataDir}) must be writable by the web server." );
}
$wgObjectCaches[CACHE_DB] = [
	'class' => SqlBagOStuff::class,
	'loggroup' => 'SQLBagOStuff',
	'server' => [
		'type' => 'sqlite',
		'dbname' => 'wikicache',
		'tablePrefix' => '',
		'variables' => [ 'synchronous' => 'NORMAL' ],
		'dbDirectory' => $wgSQLiteDataDir,
		'trxMode' => 'IMMEDIATE',
		'flags' => 0
	]
];
$wgLocalisationCacheConf['storeServer'] = [
	'type' => 'sqlite',
	'dbname' => "{$wgDBname}_l10n_cache",
	'tablePrefix' => '',
	'variables' => [ 'synchronous' => 'NORMAL' ],
	'dbDirectory' => $wgSQLiteDataDir,
	'trxMode' => 'IMMEDIATE',
	'flags' => 0
];
$wgJobTypeConf['default'] = [
	'class' => 'JobQueueDB',
	'claimTTL' => 3600,
	'server' => [
		'type' => 'sqlite',
		'dbname' => "{$wgDBname}_jobqueue",
		'tablePrefix' => '',
		'variables' => [ 'synchronous' => 'NORMAL' ],
		'dbDirectory' => $wgSQLiteDataDir,
		'trxMode' => 'IMMEDIATE',
		'flags' => 0
	]
];


# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = false;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/opt/homebrew/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = false;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "en";

# Time zone
$wgLocaltimezone = "UTC";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
$wgCacheDirectory = "$IP/cache";

## Use file-based localisation cache to avoid SQLite l10n_cache issues in dev
$wgLocalisationCacheConf['store'] = 'array';
$wgLocalisationCacheConf['storeDirectory'] = $wgCacheDirectory;

$wgSecretKey = "3ac97a75ef137a878ddbbd165976ed71b71b830fc0299889efe6f86156eee467";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "99c66af6c08320d6";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = "citizen";

# Enable UniversalLanguageSelector extension (required by Translate)
wfLoadExtension( 'UniversalLanguageSelector' );

# Enable Translate extension
wfLoadExtension( 'Translate' );

# Basic Translate extension configuration
$wgTranslateDocumentationLanguageCode = 'en';
$wgEnablePageTranslation = true;
$wgGroupPermissions['user']['translate'] = true;
$wgGroupPermissions['sysop']['pagetranslation'] = true;

# Basic UniversalLanguageSelector configuration
$wgULSEnable = true;
$wgULSAnonCanChangeLanguage = true;

# Enabled skins:
 wfLoadSkin( 'Citizen' );
# wfLoadSkin( 'MinervaNeue' );
# wfLoadSkin( 'MonoBook' );
# wfLoadSkin( 'Timeless' );
# wfLoadSkin( 'Vector' );
# wfLoadSkin( 'Evelution' );


# End of automatically generated settings.
# Add more configuration options below.

# Enable detailed error reporting for debugging
$wgShowExceptionDetails = true;
$wgShowDBErrorBacktrace = true;
$wgDevelopmentWarnings = true;
$wgShowSQLErrors = true;
error_reporting(E_ALL);
ini_set('display_errors', 1);
ini_set('log_errors', 1);
ini_set('error_log', "$IP/logs/error.log");
ini_set( 'memory_limit', '512M' );

# Load CreateWiki and ManageWiki extensions for wiki farm functionality
wfLoadExtension('CreateWiki');
wfLoadExtension('ManageWiki');

// Load custom CSS
$wgHooks['BeforePageDisplay'][] = function ( OutputPage $out, Skin $skin ) {
    $out->addHeadItem(
        'custom-css',
        '<link rel="stylesheet" href="/resources/src/custom/custom.css">'
    );
    return true;
};

# CreateWiki configuration
$wgCreateWikiGlobalWiki = 'azwiki';
$wgCreateWikiDatabase = '$1wiki';
$wgCreateWikiSubdomain = '$1.13.233.126.84';
$wgCreateWikiUsePrivateWikis = false;
$wgCreateWikiDisableCreateWiki = false;
$wgCreateWikiDisableManageWiki = false;
$wgCreateWikiCacheDirectory = "$IP/cache/createwiki";
$wgCreateWikiCacheType = CACHE_NONE; // Disable caching
# Disable database clusters for simple SQLite setup
$wgCreateWikiDatabaseClusters = [];

# Set this wiki as the central wiki
$wgCreateWikiCentralWiki = true;

# Configure SQL files for new wiki creation
$wgCreateWikiSQLFiles = [
    "$IP/sql/sqlite/tables-generated.sql"
];

# Simple database configuration for CreateWiki without clusters

# ManageWiki configuration
$wgManageWikiPermissionsManagement = true;
$wgManageWikiExtensions = true;
$wgManageWikiSettings = true;
$wgManageWikiCacheDirectory = "$IP/cache/managewiki";

# User permissions for wiki creation
$wgGroupPermissions['user']['createwiki'] = true;
$wgGroupPermissions['*']['createwiki'] = true;

# Wiki routing configuration
$wgCreateWikiUseEchoNotifications = false;
$wgCreateWikiShowBiographicalOption = false;

# Proper subdomain handling - Updated to match CreateWiki naming pattern
if (isset($_SERVER['HTTP_HOST'])) {
    $host = $_SERVER['HTTP_HOST'];
    if (preg_match('/^([a-z0-9-]+)\.13.233.126.84$/', $host, $matches)) {
        $subdomain = $matches[1];
        if ($subdomain !== 'www' && $subdomain !== 'main') {
            // Check for both naming patterns: 'azwiki' and 'my_wiki_az'
            $wikiDbName1 = $subdomain . 'wiki';  // e.g. azwiki
            $wikiDbName2 = 'my_wiki_' . $subdomain;  // e.g. my_wiki_az
            
            $dbFile1 = "$IP/data/{$wikiDbName1}.sqlite";
            $dbFile2 = "$IP/data/{$wikiDbName2}.sqlite";
            
                        // Check which database file exists
            if (file_exists($dbFile1) && filesize($dbFile1) > 0) {
                $wgDBname = $wikiDbName1;
                $wgSitename = ucfirst($subdomain) . ' Wiki';
                $currentDbFile = $dbFile1;
            } elseif (file_exists($dbFile2) && filesize($dbFile2) > 0) {
                $wgDBname = $wikiDbName2;
                $wgSitename = ucfirst($subdomain) . ' Wiki';
                $currentDbFile = $dbFile2;
            } else {
                // Wiki doesn't exist, show error
                if (!defined('MW_NO_OUTPUT_BUFFER')) {
                    define('MW_NO_OUTPUT_BUFFER', true);
                }
                header('HTTP/1.1 404 Not Found');
                echo "<!DOCTYPE html><html><head><title>Wiki Not Found</title></head><body>";
                echo "<h1>Wiki Not Found</h1>";
                echo "<p>The wiki '{$subdomain}' does not exist.</p>";
                echo "<p><a href='http://13.233.126.84/index.php/Special:CreateWiki'>Create a new wiki</a></p>";
                echo "</body></html>";
                exit;
            }
        }
    }
}

# Enable uploads for better wiki functionality
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/opt/homebrew/bin/convert";

# WikiInitialize setup for CreateWiki farm - TEMPORARILY DISABLED FOR TESTING
# require_once "$IP/extensions/CreateWiki/includes/WikiInitialize.php";

# use Miraheze\CreateWiki\WikiInitialize;

# $wgConf = new WikiInitialize();

# Set up wiki farm configuration
# $wmgCacheDirectory = "$IP/cache/createwiki";
# $wmgSuffixes = [ 'main' => 'main' ];
# $wmgSiteMatch = [ '13.233.126.84' => 'main' ];

# $wgConf->setVariables(
#     $wmgCacheDirectory,
#     $wmgSuffixes,
#     $wmgSiteMatch
# );

# Read cache for current wiki
# $wgConf->readCache();

# Apply configuration
# $wgConf->config->extractAllGlobals( $wgConf->dbname );

# Keep the existing database name if WikiInitialize doesn't provide one
# if ( $wgConf->dbname ) {
#     $wgDBname = $wgConf->dbname;
# } else {
#     # Fallback to the existing database name
#     $wgDBname = "my_wiki_main";
# }

# Set server and sitename from WikiInitialize
# if ( $wgConf->server ) {
#     $wgServer = $wgConf->server;
# }

# if ( $wgConf->sitename ) {
#     $wgSitename = $wgConf->sitename;
# }

# Simple virtual domain mapping for CreateWiki
# CreateWiki central operations should always use the main database
$wgVirtualDomainsMapping = [
    'virtual-createwiki' => [ 'db' => 'azwiki' ],
    'virtual-createwiki-central' => [ 'db' => 'azwiki' ]
];

// Function to ensure AbuseFilter tables exist
function ensureAbuseFilterTables($dbName, $dbFile) {
    global $IP;
    
    // Skip if we've already checked this database in this request
    static $checkedDbs = [];
    if (in_array($dbName, $checkedDbs)) {
        return;
    }
    $checkedDbs[] = $dbName;
    
    // Skip if we're in maintenance mode or the database file doesn't exist
    if (defined('MW_NO_SESSION') || !file_exists($dbFile)) {
        return;
    }
    
    // Check if abuse_filter table exists
    $db = new SQLite3($dbFile);
    $result = $db->query("SELECT name FROM sqlite_master WHERE type='table' AND name='abuse_filter'");
    $tableExists = $result->fetchArray() !== false;
    
    if (!$tableExists) {
        // If the table doesn't exist, run the update script
        $cmd = sprintf(
            'cd %s && php maintenance/run.php ensureAbuseFilterTables --wiki=%s',
            escapeshellarg($IP),
            escapeshellarg($dbName)
        );
        exec($cmd, $output, $returnVar);
        
        if ($returnVar !== 0) {
            error_log("Failed to ensure AbuseFilter tables for $dbName: " . implode("\n", $output));
        }
    }
    
    $db->close();
}

// Call the function to ensure tables exist for the current wiki
if (isset($currentDbFile) && isset($wgDBname)) {
    ensureAbuseFilterTables($wgDBname, $currentDbFile);
}

wfLoadExtension( 'Echo' );
wfLoadExtension( 'AbuseFilter' );
wfLoadExtension( 'Gadgets' );
wfLoadExtension( 'Translate' );
wfLoadExtension( 'CreatePage' );
wfLoadExtension( 'ContactPage' );
wfLoadExtension( 'UniversalLanguageSelector' );

$wgEvelutionShowPageTools = true;
$wgEvelutionDisableRightRail = true;
$wgEvelutionForceFullWidth = false;
$wgEvelutionChangeMessageBoxesToBanners	= true;

$wgGroupPermissions['bureaucrat']['userrights'] = true;
$wgGroupPermissions['*']['bureaucrat'] = true;
$wgGroupPermissions['*']['sysop'] = true;
$wgGroupPermissions['*']['editinterface'] = true;
$wgGroupPermissions['*']['editsitecss'] = true;
$wgGroupPermissions['*']['editsitejs'] = true;

