<?php
// Automatically generated by CreateWiki
return [
	'mtime' => 1758137936,
	'databases' => [
		'movies_wiki' => [
			's' => 'Movies Wiki',
			'c' => 'c1',
			'u' => 'movies.localhost:4000',
		],
		'games_wiki' => [
			's' => 'Games Wiki',
			'c' => 'c1',
			'u' => 'games.localhost:4000',
		],
		'books_wiki' => [
			's' => 'Books Wiki',
			'c' => 'c1',
			'u' => 'books.localhost:4000',
		],
		'tech_wiki' => [
			's' => 'Tech Wiki',
			'c' => 'c1',
			'u' => 'tech.localhost:4000',
		],
		'my_wiki' => [
			's' => 'GnosPedia Main',
			'c' => 'c1',
			'u' => 'localhost:4000',
		],
	],
];
