<?php
// Automatically generated by CreateWiki
return [
	'mtime' => 1759080323,
	'databases' => [
		'my_wiki' => [
			's' => 'GnosPedia',
			'c' => 'c1',
		],
		'logicwiki' => [
			's' => 'Logic Wiki',
			'c' => null,
		],
		'ewiki' => [
			's' => 'ew',
			'c' => null,
		],
		'fanwiki' => [
			's' => 'Fan',
			'c' => null,
		],
	],
];
